# Generated by Django 5.1.2 on 2024-10-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_alter_note_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
